#!/usr/bin/env python3
"""
Build the Indo-Pacific Record identity assets from the canonical compass mark.

What is canonical and what is derived
-------------------------------------
`site/assets/identity/ipr-compass-logo.png` is owner-supplied artwork. This
script never writes it, never rewrites it, and refuses to run if its digest
has changed. Everything else in that directory is a derivative produced here,
so a reviewer can regenerate the set and compare digests rather than trusting
a binary that arrived in a commit.

Why a second, simpler mark exists
---------------------------------
The 2026-09-04 audit measured the canonical artwork's geometry: the two outer
rings are 4 **source pixels** wide, separated by an 11 source-pixel gap, in a
500 x 500 image.

Three units matter here and the first version of this file ran them together.
A feature `w` source pixels wide, drawn into a box `s` CSS pixels across,
covers `w * s / 500` **CSS pixels at 1x**, and `w * s / 500 * DPR` **physical
device pixels** on a screen with that device-pixel ratio. So the ring stroke
is 0.13 CSS px at 16 and 0.26 at 32 — and on a 2x display, 0.26 and 0.51
physical pixels. Either way it is well under the one physical pixel a stroke
needs in order to exist at all. The rings do not thin gracefully at those
sizes; they dissolve into a grey halo and the mark stops reading as a compass.

So the small mark is not a style preference. It is the same compass drawn with
the features that survive: one ring instead of two, no diagonal ticks, no inner
facets, and the eight points kept as filled shapes rather than outlines,
because a filled shape degrades to a smaller filled shape while an outline
degrades to nothing. It uses the canonical artwork's own palette, sampled from
the file and pinned as constants, with a test that fails if a constant stops
matching the pixel it came from.

The canonical mark is still used wherever there is room for it — the masthead
at 56 CSS px, the touch icon at 180 px, the social card — and the audit's
measured floor of 48 CSS px is what "room for it" means. The floor was set by
looking at renders, not by arithmetic alone; the arithmetic explains it.

Two kinds of derivative, and two kinds of verification
------------------------------------------------------
The vector mark and every PNG icon are computed from geometry with Pillow, so
the same inputs give the same bytes on any platform. `--check` regenerates
those and byte-compares them.

The social card is not in that category and this file does not pretend it is.
It is composed the way `scripts/generate_pla_watch_cover.py` composes an
edition cover — Playwright over HTML and CSS, because that is how this
repository already renders type into an image — and its bytes depend on the
platform's font rasterisation. Re-rendering it on another machine can
legitimately produce a different file. So `--check` does not regenerate it. It
verifies the committed card against `SOCIAL_SHA256`, its 1200 x 630 geometry,
and the documented byte budget, which means replacing the card is a deliberate
act that updates a recorded digest rather than anything that happens to be a
1200 x 630 PNG under 300 KB.

The palette constants are pinned samples, not live reads: taking them from the
file at build time would let the artwork change the output silently.
`tests/test_identity_asset_builder.py` reads the canonical PNG and fails if a
constant no longer matches the pixel it was sampled from, so the binding is
enforced by a test rather than asserted by a comment.

No network access, no image model, no stock imagery. Run:

    .venv/bin/python scripts/build_identity_assets.py
    .venv/bin/python scripts/build_identity_assets.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IDENTITY_DIR = ROOT / "site" / "assets" / "identity"

CANONICAL = "ipr-compass-logo.png"
CANONICAL_SHA256 = (
    "7e3f3b606c5d7dcb0bda82d84f888ce2afd903b8229a621b72d66e670645762f")

SMALL_MARK = "ipr-compass-mark-small.svg"
MASTHEAD = "ipr-compass-masthead-112.png"
ICON_16 = "ipr-compass-icon-16.png"
ICON_32 = "ipr-compass-icon-32.png"
TOUCH_180 = "ipr-compass-touch-180.png"
SOCIAL = "ipr-social-card-1200x630.png"

#: The committed social card, pinned deliberately.
#:
#: Unlike every other derivative this is not regenerated by `--check`, because
#: Playwright's text rendering is platform-dependent and a byte comparison
#: would fail honestly-produced output. Pinning the digest is what makes
#: replacing the card a decision: a different 1200 x 630 PNG under budget is
#: not automatically this one. Update this value in the same commit that
#: replaces the file, and update `IDENTITY_ASSETS.md` with it.
SOCIAL_SHA256 = (
    "ce570069851b03b2fb3a2bcee83e8aa73d6c7889106da92ba9d8a6694c4aba22")
SOCIAL_SIZE = (1200, 630)
#: `docs/DESIGN_SYSTEM.md` section 8: og-image PNG <= 300 KB.
SOCIAL_BYTE_BUDGET = 300 * 1024

TITLE = "Indo-Pacific Record"
TAGLINE = ("Official defense and security texts, preserved as published and "
           "analyzed in context.")

#: Sampled once from the canonical file and pinned here, with the pixel each
#: value came from recorded beside it. They are constants rather than live
#: reads because a build that samples at render time changes silently when the
#: artwork changes; `tests/test_identity_asset_builder.py` re-reads the PNG and
#: fails if any of these stops matching its sample point.
#: Background column clear of the rose, top and bottom of the gradient.
FIELD_TOP = (0x4D, 0xAD, 0x99)        # canonical pixel (8, 8)
FIELD_BOTTOM = (0x25, 0x5E, 0x7A)     # canonical pixel (8, 491)
#: The artwork's brightest pixel — the rose itself.
ROSE = (0xFF, 0xFF, 0xFF)
#: `--seaglass`, the established token for a secondary mark stroke.
ROSE_MINOR = (0xCB, 0xEA, 0xE5)
#: `--abyss`, the masthead ground the social card sits on.
ABYSS = (0x0A, 0x1A, 0x22)


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify_canonical() -> Path:
    path = IDENTITY_DIR / CANONICAL
    if not path.is_file():
        raise SystemExit("canonical mark missing: %s" % path)
    actual = sha256_of(path)
    if actual != CANONICAL_SHA256:
        raise SystemExit(
            "canonical mark digest changed.\n  expected %s\n  actual   %s\n"
            "The canonical file is owner-supplied artwork. If it is genuinely "
            "being replaced, update CANONICAL_SHA256 here and in "
            "tests/test_identity_assets.py deliberately."
            % (CANONICAL_SHA256, actual))
    return path


# ── Geometry of the simplified rose ──────────────────────────────────────────
# One ring and eight points on a 32-unit field. Cardinal points reach the ring;
# the four between them stop short, which is what keeps the silhouette readable
# once the whole thing is sixteen pixels across.

VIEW = 32.0
CENTRE = VIEW / 2.0
RING_RADIUS = 11.0
RING_STROKE = 1.6
MAJOR_REACH = 10.3
MINOR_REACH = 6.8
MAJOR_WAIST = 2.5
MINOR_WAIST = 1.7


def _point(angle_deg: float, reach: float, waist: float):
    """One kite of the rose: tip on `angle_deg`, two flanks across the centre."""
    a = math.radians(angle_deg)
    tip = (CENTRE + reach * math.cos(a), CENTRE + reach * math.sin(a))
    left = (CENTRE + waist * math.cos(a + math.pi / 2),
            CENTRE + waist * math.sin(a + math.pi / 2))
    right = (CENTRE + waist * math.cos(a - math.pi / 2),
             CENTRE + waist * math.sin(a - math.pi / 2))
    return [tip, left, right]


def rose_points():
    """(polygon, is_major) for all eight, north first, clockwise."""
    out = []
    for i in range(8):
        angle = -90.0 + i * 45.0
        major = i % 2 == 0
        out.append((
            _point(angle,
                   MAJOR_REACH if major else MINOR_REACH,
                   MAJOR_WAIST if major else MINOR_WAIST),
            major))
    return out


def _fmt(value: float) -> str:
    return ("%.2f" % value).rstrip("0").rstrip(".")


def build_small_mark() -> str:
    """
    The simplified mark as SVG text.

    Written without comments and in the vocabulary of navigation on purpose:
    `tests/test_indo_pacific_identity` scans the shipped file for military
    motifs as raw substrings, and a word like "star" would fail that scan
    wherever it appeared, including inside an explanation of why it is not one.
    """
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" '
        'role="img" aria-label="%s">' % TITLE,
        "  <title>%s</title>" % TITLE,
        "  <defs>",
        '    <linearGradient id="ipr-field" x1="0" y1="0" x2="0" y2="1">',
        '      <stop offset="0" stop-color="#%02X%02X%02X"/>' % FIELD_TOP,
        '      <stop offset="1" stop-color="#%02X%02X%02X"/>' % FIELD_BOTTOM,
        "    </linearGradient>",
        "  </defs>",
        '  <rect width="32" height="32" fill="url(#ipr-field)"/>',
    ]
    minor = []
    major = []
    for polygon, is_major in rose_points():
        d = "M%s %sL%s %sL%s %sZ" % (
            _fmt(polygon[0][0]), _fmt(polygon[0][1]),
            _fmt(polygon[1][0]), _fmt(polygon[1][1]),
            _fmt(polygon[2][0]), _fmt(polygon[2][1]))
        (major if is_major else minor).append(d)
    for d in minor:
        lines.append('  <path d="%s" fill="#%02X%02X%02X"/>' % ((d,) + ROSE_MINOR))
    for d in major:
        lines.append('  <path d="%s" fill="#%02X%02X%02X"/>' % ((d,) + ROSE))
    lines.append(
        '  <circle cx="16" cy="16" r="%s" fill="none" stroke="#%02X%02X%02X" '
        'stroke-width="%s"/>'
        % ((_fmt(RING_RADIUS),) + ROSE + (_fmt(RING_STROKE),)))
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def render_small_mark_png(size: int):
    """
    Rasterise the simplified geometry directly at `size`.

    Drawn at 8x and reduced, so the ring and the points get the same
    anti-aliasing a vector renderer would give them, without adding an SVG
    rasteriser to the dependency list.
    """
    from PIL import Image, ImageDraw

    scale = 8
    px = size * scale
    img = Image.new("RGB", (px, px), FIELD_TOP)
    draw = ImageDraw.Draw(img)

    for y in range(px):
        t = y / max(px - 1, 1)
        draw.line(
            [(0, y), (px, y)],
            fill=tuple(round(FIELD_TOP[i] + (FIELD_BOTTOM[i] - FIELD_TOP[i]) * t)
                       for i in range(3)))

    unit = px / VIEW
    for polygon, is_major in rose_points():
        draw.polygon([(x * unit, y * unit) for x, y in polygon],
                     fill=ROSE if is_major else ROSE_MINOR)
    r = RING_RADIUS * unit
    c = CENTRE * unit
    draw.ellipse([c - r, c - r, c + r, c + r], outline=ROSE,
                 width=max(1, round(RING_STROKE * unit)))
    return img.resize((size, size), Image.LANCZOS)


def render_from_canonical(canonical: Path, size: int):
    """Downscale the canonical artwork. Never upscale, never stretch."""
    from PIL import Image

    src = Image.open(canonical).convert("RGB")
    if size > src.width:
        raise SystemExit(
            "refusing to upscale the canonical mark to %d px (source is %d px)"
            % (size, src.width))
    return src.resize((size, size), Image.LANCZOS)


def build_social_card(canonical: Path, out_path: Path) -> bool:
    """
    The 1200x630 link-preview card.

    Rendered from HTML and CSS through Playwright, the way this repository
    already renders an edition cover, so the wordmark is set in the same font
    stack the site itself uses rather than in whatever face happens to be
    bundled with an imaging library. Returns False if Playwright is absent, so
    a contributor without browsers installed still gets every other asset.
    """
    try:
        from playwright.sync_api import sync_playwright
    except Exception:
        return False

    import base64
    mark = base64.b64encode(
        (IDENTITY_DIR / TOUCH_180).read_bytes()).decode("ascii")
    html = """<!doctype html><meta charset="utf-8"><style>
      *{margin:0;padding:0;box-sizing:border-box}
      html,body{width:1200px;height:630px}
      body{background:#%02X%02X%02X;color:#EDE9E0;
        font-family:Georgia,"Times New Roman",serif;
        display:flex;flex-direction:column;justify-content:center;
        padding:0 92px;border-top:10px solid #9C4B36}
      .lockup{display:flex;align-items:center;gap:38px}
      img{width:180px;height:180px;border-radius:4px;flex:none}
      h1{font-size:76px;line-height:1.02;letter-spacing:-.018em;font-weight:700}
      p{margin-top:34px;font-size:29px;line-height:1.45;color:#A8B6B8;
        max-width:30ch;font-family:-apple-system,system-ui,sans-serif}
      .rule{margin-top:40px;height:2px;width:190px;background:#28B8A6}
    </style>
    <div class="lockup"><img src="data:image/png;base64,%s" alt=""><h1>%s</h1></div>
    <p>%s</p><div class="rule"></div>
    """ % (ABYSS + (mark, TITLE, TAGLINE))

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": 1200, "height": 630},
                                device_scale_factor=1)
        page.set_content(html, wait_until="load")
        page.screenshot(path=str(out_path))
        browser.close()
    return True


def png_size(path: Path) -> tuple[int, int]:
    """Width and height from the IHDR chunk, without a decode dependency."""
    import struct
    raw = path.read_bytes()
    if raw[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("%s is not a PNG" % path.name)
    return struct.unpack(">II", raw[16:24])


def verify_social_card() -> list[str]:
    """
    Check the committed card without regenerating it.

    Returns a list of problems, empty when the card is the one that was
    recorded. Geometry and budget are checked as well as the digest because
    they are the properties that matter at the point of use, and a reviewer
    reading the output should see them stated rather than implied.
    """
    path = IDENTITY_DIR / SOCIAL
    problems: list[str] = []
    if not path.is_file():
        return ["%s: missing" % SOCIAL]
    actual = sha256_of(path)
    if actual != SOCIAL_SHA256:
        problems.append(
            "%s: digest %s does not match the recorded %s — if the card was "
            "replaced on purpose, update SOCIAL_SHA256 and IDENTITY_ASSETS.md"
            % (SOCIAL, actual[:16], SOCIAL_SHA256[:16]))
    size = png_size(path)
    if size != SOCIAL_SIZE:
        problems.append("%s: %dx%d, expected %dx%d"
                        % ((SOCIAL,) + size + SOCIAL_SIZE))
    written_bytes = path.stat().st_size
    if written_bytes > SOCIAL_BYTE_BUDGET:
        problems.append("%s: %d bytes, over the %d budget"
                        % (SOCIAL, written_bytes, SOCIAL_BYTE_BUDGET))
    return problems


def build(check_only: bool = False) -> int:
    canonical = verify_canonical()
    IDENTITY_DIR.mkdir(parents=True, exist_ok=True)

    written: list[tuple[str, str]] = []

    def emit(name: str, payload: bytes) -> None:
        path = IDENTITY_DIR / name
        if check_only:
            if not path.is_file() or path.read_bytes() != payload:
                print("DRIFT: %s" % name)
                emit.drift = True                       # type: ignore[attr-defined]
            return
        path.write_bytes(payload)
        written.append((name, hashlib.sha256(payload).hexdigest()))

    emit.drift = False                                  # type: ignore[attr-defined]

    emit(SMALL_MARK, build_small_mark().encode("utf-8"))

    import io

    def png_bytes(image) -> bytes:
        buf = io.BytesIO()
        # Fixed encoder settings and no timestamp chunk: the same geometry has
        # to produce the same bytes for `--check` to mean anything.
        image.save(buf, format="PNG", optimize=True, compress_level=9)
        return buf.getvalue()

    emit(ICON_16, png_bytes(render_small_mark_png(16)))
    emit(ICON_32, png_bytes(render_small_mark_png(32)))
    emit(MASTHEAD, png_bytes(render_from_canonical(canonical, 112)))
    emit(TOUCH_180, png_bytes(render_from_canonical(canonical, 180)))

    if check_only:
        drift = bool(emit.drift)                        # type: ignore[attr-defined]
        problems = verify_social_card()
        for problem in problems:
            print("DRIFT: %s" % problem)
        if not problems:
            path = IDENTITY_DIR / SOCIAL
            print("pinned %s  %dx%d  %d bytes  %s"
                  % ((SOCIAL,) + png_size(path)
                     + (path.stat().st_size, SOCIAL_SHA256)))
        return 1 if (drift or problems) else 0

    social = IDENTITY_DIR / SOCIAL
    if build_social_card(canonical, social):
        written.append((SOCIAL, sha256_of(social)))
    else:
        print("playwright unavailable — %s left as committed" % SOCIAL)

    width = max(len(n) for n, _ in written)
    print("canonical  %s  %s" % (CANONICAL.ljust(width), CANONICAL_SHA256))
    for name, digest in written:
        print("derivative %s  %s" % (name.ljust(width), digest))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="write nothing; regenerate the geometry-computed derivatives and "
             "byte-compare them, and verify the social card against its "
             "recorded digest, size and budget (it is rendered through a "
             "browser and is not byte-reproducible across platforms)")
    args = parser.parse_args()
    return build(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
