"""Build *private* Vietnam Briefs model candidates from a verified MPS review queue.

Consumes the separately audited, metadata-only queue generated by
prepare_vietnam_mps_review_queue.py and a human-authored *research synopsis*
catalog. Never fetches publisher sites, opens production DBs, uses an LLM,
asserts publication approval or sends email.

The resulting JSON has the same per-source shape as PR #203's
core.brief_editorial_evidence packet. Rebuilding it for future weeks requires
a fresh verified queue and matching source-version synopsis entries.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import date
from pathlib import Path
from urllib.parse import urlsplit

SCHEMA = "ipr-private-drafting-evidence/1"
STATUS = "unapproved-source-linked-editorial-candidate"
SCOPE = "private-model-drafting-only-no-source-body"
QUEUE_SCHEMA = "vietnam-mps-pilot-review-queue/1"
SOURCE = "vn_mps_foreign_affairs_vi"
HEX40 = re.compile(r"[0-9a-f]{40}\Z")
HEX64 = re.compile(r"[0-9a-f]{64}\Z")
FIELDS = {"id", "desk", "source_name", "source_url", "published_date",
          "language", "title_original", "source_kind", "state_commit",
          "source_content_sha256", "hash_rule", "summary", "caveats",
          "topics", "status", "copy_scope"}
MAX_VIETNAM = 3
TOPICS = {
    "hadr", "defense_exercises", "alliance_diplomacy", "maritime_security",
    "technology_cooperation", "security_industry", "regional_partnerships",
}


class VietnamFeederError(ValueError):
    pass


def require(condition, message):
    if not condition:
        raise VietnamFeederError(message)


def pairs(items):
    output = {}
    for key, value in items:
        require(key not in output, "duplicated JSON field")
        output[key] = value
    return output


def load(path, max_bytes):
    file = Path(path)
    require(file.is_file() and not file.is_symlink()
            and file.stat().st_size <= max_bytes, "unsafe or oversized input")
    try:
        return json.loads(file.read_text(encoding="utf-8"), object_pairs_hook=pairs)
    except (ValueError, UnicodeError) as exc:
        raise VietnamFeederError("invalid JSON/encoding") from exc


def canonical_json(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def window(value):
    try:
        d = date.fromisoformat(value)
    except (TypeError, ValueError) as exc:
        raise VietnamFeederError("invalid reporting week") from exc
    require(d.isoformat() == value and d.weekday() == 5, "week must end Saturday")
    return d


def verified_queue(queue):
    require(isinstance(queue, dict) and queue.get("schema") == QUEUE_SCHEMA
            and queue.get("source_slug") == SOURCE,
            "not the MPS foreign-affairs verified queue")
    require(queue.get("state_branch") == "shadow/vietnam-mps-foreign-affairs",
            "foreign shadow branch")
    require(isinstance(queue.get("state_commit"), str) and
            HEX40.fullmatch(queue["state_commit"]), "unverified source commit")
    require(isinstance(queue.get("state_tree"), str) and
            HEX40.fullmatch(queue["state_tree"]), "unverified source tree")
    require(queue.get("successful_run_count", 0) > 0 and
            queue.get("record_count", 0) >= 0 and
            queue.get("human_approvals") == 0 and
            queue.get("rights_approvals") == 0 and
            queue.get("automatic_production_admission") is False and
            queue.get("full_desk_qualification") is False and
            queue.get("original_article_bodies_in_packet") is False,
            "queue incorrectly claims approval or production qualification")
    digest = queue.get("queue_sha256")
    without_digest = {k: v for k, v in queue.items() if k != "queue_sha256"}
    require(isinstance(digest, str) and
            HEX64.fullmatch(digest) and
            hashlib.sha256(canonical_json(without_digest).encode()).hexdigest() == digest,
            "queue canonical hash mismatch")
    rows = queue.get("records")
    require(isinstance(rows, list) and len(rows) == queue["record_count"],
            "queue inventory mismatch")
    return rows


def make_packet(queue, authored, week_ending, *, previous=None):
    """Join an audited metadata queue to version-bound research notes.

    The original review queue has already undergone its independent Git-tree,
    SQLite, source-version and capture validation. Never reconstruct a queue
    from raw unreviewed filenames or pretend this hash validates live URLs.
    """
    saturday = window(week_ending)
    sunday = saturday.fromordinal(saturday.toordinal() - 6)
    rows = verified_queue(queue)
    require(isinstance(authored, dict) and
            authored.get("schema") == "vietnam-editorial-notes/1" and
            isinstance(authored.get("entries"), list), "invalid editorial notes")
    notes = authored["entries"]
    require(len(notes) <= 20, "editorial note catalog is oversized")
    ids = [n.get("source_identity") for n in notes if isinstance(n, dict)]
    require(len(set(ids)) == len(ids), "duplicate notes")
    indexed = {n["source_identity"]: n for n in notes}
    selected = []
    for row in rows:
        if not row.get("machine_review_candidate") or row.get("machine_blockers"):
            continue
        try:
            published = date.fromisoformat(row["published_date"])
        except (TypeError, ValueError):
            continue
        if not (sunday <= published <= saturday):
            continue
        note = indexed.get(row["source_identity"])
        if note is None:
            continue   # No source-specific synopsis: do not invent prose.
        identity = row["source_identity"]
        require(isinstance(identity, str) and re.fullmatch(r"mps-vi:\d{10}", identity),
                "invalid MPS article identifier")
        url = row["canonical_url"]
        u = urlsplit(url)
        require(u.scheme == "https" and u.hostname == "bocongan.gov.vn"
                and u.port is None and not u.query and not u.fragment
                and not u.username and not u.password and
                u.path.endswith("-" + identity.partition(":")[2])
                and u.path.startswith("/bai-viet/"), "noncanonical MPS source URL")
        require(row["source_slug"] == SOURCE and row["body_status"] == "text"
                and row["human_source_reviewed"] is False
                and row["reuse_rights_reviewed"] is False
                and row["production_publication_authorized"] is False,
                "source status must remain unapproved and original-text")
        require(note.get("content_sha256") == row["content_sha256"]
                and note.get("source_url") == url
                and note.get("published_date") == row["published_date"],
                "research note not pinned to current source version")
        summary = note.get("summary")
        caveats = note.get("caveats")
        topics = note.get("topics")
        require(isinstance(summary, str) and 65 <= len(summary) <= 700
                and "\n" not in summary, "original brief synopsis invalid")
        require(isinstance(caveats, list) and 1 <= len(caveats) <= 4
                and all(isinstance(c, str) and 15 <= len(c) <= 270 and
                        "\n" not in c for c in caveats), "source caveats invalid")
        require(isinstance(topics, list) and 1 <= len(topics) <= 3
                and all(isinstance(t, str) for t in topics)
                and len(set(topics)) == len(topics) and
                set(topics).issubset(TOPICS), "topic labels invalid")
        selected.append({
            "id": "VN-MPS-" + identity.partition(":")[2],
            "desk": "vietnam",
            "source_name": "Vietnam Ministry of Public Security",
            "source_url": url,
            "published_date": row["published_date"],
            "language": "vi",
            "title_original": row["title_original"],
            "source_kind": "shadow-extracted-original",
            "state_commit": queue["state_commit"],
            "source_content_sha256": row["content_sha256"],
            "hash_rule": "mps-vi-content-v1",
            "summary": summary,
            "caveats": caveats,
            "topics": topics,
            "status": STATUS,
            "copy_scope": SCOPE,
        })
    selected.sort(key=lambda x: (x["published_date"], x["id"]), reverse=True)
    selected = selected[:MAX_VIETNAM]
    packet = previous if previous is not None else {
        "schema": SCHEMA, "week_ending": week_ending, "status": STATUS, "items": [],
    }
    require(isinstance(packet, dict) and packet.get("schema") == SCHEMA
            and packet.get("week_ending") == week_ending
            and packet.get("status") == STATUS
            and isinstance(packet.get("items"), list),
            "cannot update incompatible weekly editorial packet")
    non_vietnam = [item for item in packet["items"]
                   if isinstance(item, dict) and item.get("desk") != "vietnam"]
    require(len(non_vietnam) == len(packet["items"]) -
            sum(isinstance(x, dict) and x.get("desk") == "vietnam"
                for x in packet["items"]), "malformed existing research item")
    require(all(set(x) == FIELDS for x in non_vietnam),
            "existing Japan entries have changed schema")
    merged = dict(packet)
    merged["items"] = non_vietnam + selected
    require(len(merged["items"]) <= 8, "combined regional research quota exceeded")
    urls = [item["source_url"] for item in merged["items"]]
    ids = [item["id"] for item in merged["items"]]
    require(len(set(urls)) == len(urls) and len(set(ids)) == len(ids),
            "duplicate official evidence after regional merge")
    return merged


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--queue", required=True, type=Path)
    parser.add_argument("--notes", required=True, type=Path)
    parser.add_argument("--week-ending", required=True)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--existing", type=Path)
    args = parser.parse_args(argv)
    require(not args.out.exists() and not args.out.is_symlink(),
            "refuse overwriting an existing candidate pack")
    previous = load(args.existing, 40000) if args.existing else None
    packet = make_packet(load(args.queue, 90000), load(args.notes, 20000),
                         args.week_ending, previous=previous)
    args.out.write_text(canonical_json(packet), encoding="utf-8")
    print("Private editorial packet: {} Vietnam candidates; no approval or mail".format(
        sum(item["desk"] == "vietnam" for item in packet["items"])))


if __name__ == "__main__":
    main()
